### ISSUE TITLE
Dark mode flips inadvertently on Wikipedia

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1590]
On the English Wikipedia there is an experimental "dark mode" available. 

Unfortunately, it seems to do the opposite to the 10ten popup, which I have set to "dark" as well.

![Wikipedia screenshot of "Japanese language"](https://github.com/birchill/10ten-ja-reader/assets/28300/6a5be5ab-1218-4c27-8b51-36a26c61cd07)

I'm using the "Vector (legacy)" Wikipedia style here, the dark/light toggle is in the top right.

**Comment by birtles** [comment]
I managed to reproduce this and it looks like Wikipedia just adds a filter to the whole page:

```css
html, html img, html video, html ogvjs, html svg, html iframe, html .mw-no-invert, html td .diffchange, html .mwe-math-element, html .wvui-typeahead-suggestion__thumbnail, html .skin-minerva .mw-notification-visible .mw-notification-content, html .cdx-menu-item__thumbnail, html .cx-slitem__image, html .mw-mmv-overlay, html .mw-mmv-pre-image, html .media-viewer .image img, html .media-viewer .mw-file-description img, html .mw-kartographer-map, html .mw-kartographer-mapDialog-map, html .oo-ui-searchWidget-results .oo-ui-iconElement-icon, html .list-thumb, html .ext-related-articles-card-list .ext-related-articles-card-thumb {
  filter: invert(1) hue-rotate(180deg)
}
```

As a result, everything under the root `html` element gets inverted.

If we could get a selector matching our popup (e.g. `#tenten-ja-window`) added to that selector it would cancel out the inversion.

More simply, perhaps we can just add our own style rule somewhere:

```css
html.client-dark-mode #tenten-ja-window {
  filter: invert(1) hue-rotate(180deg);
}
```
